# タスク管理アプリ用 Docker Compose設定
version: '3.8'

services:
  # PostgreSQLデータベース
  database:
    image: postgres:15-alpine
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanager"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPIバックエンド
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/taskmanager
      PYTHONPATH: /app
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./app/backend:/app
    networks:
      - taskmanager-network
    restart: unless-stopped

  # React Router V7フロントエンド
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    networks:
      - taskmanager-network
    restart: unless-stopped

# ボリューム定義
volumes:
  postgres_data:
    driver: local

# ネットワーク定義
networks:
  taskmanager-network:
    driver: bridge